language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly"

install:
  - pip install --upgrade pytest codecov pytest-cov
  - pip install -e .

script:
  - pytest --cov .
  - dailyblink

after_success:
  - codecov
